version: '3.8'

services:
  frontend:
    container_name: devops-frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "5001:5001"
    depends_on:
      - mysql


  backend:
    container_name: devops-backend
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mysql


  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: megasupersecretpassword
      MYSQL_USER: devops
      MYSQL_PASSWORD: devops
      MYSQL_DATABASE: Devops