apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: {{ .Values.backend.serviceType }}
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000