apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: {{ .Values.frontend.repCount }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: {{ .Values.frontend.imageName }}
        ports:
        - containerPort: 5001
        env:
          - name: MYSQL_USERNAME
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: mysql-username
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: mysql-password
          - name: MYSQL_SERVER
            valueFrom:
              configMapKeyRef:
                name: mysql-configmap
                key: database_url
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: {{ .Values.frontend.serviceType }}
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 5001
    targetPort: 5001