apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-username: {{ default "" .Values.mysql.username | b64enc | quote }}
  mysql-password: {{ default "" .Values.mysql.password | b64enc | quote }}
