apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: {{ .Values.mysql.imageName }}
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: megasupersecretpassword
        - name: MYSQL_USER
          value: {{ default "" .Values.mysql.username | b64enc | quote }}
        - name: MYSQL_PASSWORD
          value: {{ default "" .Values.mysql.password | b64enc | quote }}
        - name: MYSQL_DATABASE
          value: Devops
---

apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  type: {{ .Values.mysql.serviceType }}
  selector:
    app: mysql
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
